// export const SIGN_IN = 'SIGN_IN';
// export const SIGN_UP = 'SIGN_UP';
// export const SIGN_OUT = 'SIGN_OUT';
// export const UPDATE_PROFILE = 'UPDATE_PROFILE';

export const REQUESTING = 'REQUESTING';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAIL = 'REQUEST_FAIL';

export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAIL = 'SIGN_IN_FAIL';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_FAIL = 'SIGN_OUT_FAIL';

export const RECEIVE_PROFILE = 'RECEIVE_PROFILE';

export const RECEIVE_LESSON_LIST = 'RECEIVE_LESSON_LIST';
export const RECEIVE_LESSON = 'RECEIVE_LESSON';

export const RECEIVE_EXERCISE_LIST = 'RECEIVE_EXERCISE_LIST';
export const CHANGE_USER_ANSWER_IN_EXERCISE = 'CHANGE_USER_ANSWER_IN_EXERCISE';
// export const ANSWER_IN_EXERCISE = 'ANSWER_IN_EXERCISE';
// export const ANSWER_AGAIN_IN_EXERCISE = 'ANSWER_AGAIN_IN_EXERCISE';
export const RECEIVE_ANSWER_IN_EXERCISE = 'RECEIVE_ANSWER_IN_EXERCISE';
export const GO_TO_NEXT_QUESTION = 'GO_TO_NEXT_QUESTION';
export const RECEIVE_EXERCISE_RESULT = 'RECEIVE_EXERCISE_RESULT';
