export const messageConstant = {
    SET_NEW_MESSAGE: 'SET_NEW_MESSAGE',
    SET_LIST_MESSAGES: 'SET_LIST_MESSAGES',
    MINITURE_CHAT_BOX: 'MINITURE_CHAT_BOX',
    SET_CONNECTION: 'SET_CONNECTION',
    SET_ID_GVTV: 'SET_ID_GVTV',
    GET_ALL_MESSAGES: 'GET_ALL_MESSAGES',
    ADD_NEW_MESSAGE: 'ADD_NEW_MESSAGE'
}
