export const messageConstant = {
    SET_NEW_MESSAGE_TEACHER: 'SET_NEW_MESSAGE_TEACHER',
    SET_LIST_MESSAGES_TEACHER: 'SET_LIST_MESSAGES_TEACHER',
    SET_CONNECTION: 'SET_CONNECTION',
    GET_ALL_MESSAGES_TEACHER: 'GET_ALL_MESSAGES_TEACHER',
    GET_ALL_USERS: 'GET_ALL_USERS',
    SET_LIST_USERS: 'SET_LIST_USERS',
    SET_CHANNEL_ACTIVE: 'SET_CHANNEL_ACTIVE',
    ADD_NEW_MESSAGE_TEACHER: 'ADD_NEW_MESSAGE_TEACHER',
    SET_LIST_USERS_ONLINE: 'SET_LIST_USER_ONLINE',
    ADD_USER_ONLINE: 'ADD_USER_ONLINE',
    ADD_USER_CHAT: 'ADD_USER_CHAT',
}
